version: '3'
services:
  s3:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: test1234
    volumes:
      - ./storage/minio:/data
    command: server /data --console-address ":9001"